// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[list].tsx";
import * as $1 from "./routes/api/search.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Bookmarks.tsx";
import * as $$1 from "./islands/Favorites.tsx";
import * as $$2 from "./islands/Header.tsx";

const manifest = {
  routes: {
    "./routes/[list].tsx": $0,
    "./routes/api/search.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Bookmarks.tsx": $$0,
    "./islands/Favorites.tsx": $$1,
    "./islands/Header.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
